### ISSUE TITLE
Store clothes data on non-volatile storage

### ISSUE THREAD

**Issue by thewillyan** [thewillyan/ecloset#2]
To improve functionality and the test process, it's very important to add a storage system as son as possible.

Due to the guidelines, we don't have much freedom on what kind of data is stored. I suggest the following template
```toml
#clothes_data.toml

[Clothing_1]
id = 1
type = "upper"
size  = "M"
sex = "U"
color = "blue"
purchase_date = "10/02/2022"
status = "stay"
price = 5000 #optional
styles = [ "winter", "summer", "party" ]
```
A blank line should be used to determine the end of a data set.

All the CRUD components should be part of the storage system, that is, we should implement the following requirements
- [x] Add data to storage
- [x] Read stored data
- [x] Update existing data
- [x] Remove stored data

All storage-related operations should be in a single, separate file. Eg: `storage.py`.
