### ISSUE TITLE
Sale and donation system

### ISSUE THREAD

**Issue by thewillyan** [thewillyan/ecloset#4]
Once the clothes are stored, the user can choose which ones he wants to donate or sell. That's where this system comes in with the following functionalities
- [x] Sell clothes
- [x] Donate clothes
- [ ] Store donated and sold clothes in a file

The donated and sold clothes are stored separately in different files. Eg: `donated_clothes.toml` and `sold_clothes.toml`.

My suggestion is to reuse the `clothes_data.toml` template:
```toml
[Clothing_1]
id = 1
type = "upper"
size  = "M"
sex = "U"
color = "blue"
resolved_date = "10/02/2022" # date of sale or donation
price = 5000 # only for sold clothes
agent = "ONG or Person" # buyer or donation receiver
```
Where the difference between a donated clothing and a sold clothing is the existence of the `price` field.

The clothes that are donated or sold are **moved** from `clothes_data.toml`  to `donated_clothes.toml` or `sold_clothes.toml`, respectively.
